FROM node:16 as builder

WORKDIR /app

# COPY the package.json file, install dependencies, run build script
COPY package.json .
RUN npm install
COPY . .
RUN ["npm", "run", "build"]


FROM nginx
EXPOSE 80
COPY --from=builder /app/public /usr/share/nginx/html
