FROM node:16 as builder

WORKDIR /app

# COPY the package.json file, install dependencies, run build script
COPY package.json .
RUN npm install
COPY . .
RUN ["npm", "run", "build"]


FROM nginx
COPY ./nginx.conf /etc/nginx/nginx.conf
COPY --from=builder /app/public /usr/share/nginx/html
EXPOSE 8080:8080
CMD ["nginx", "-g", "daemon off;"]
