site_name: BC Government Private Cloud Technical Documentation
docs_dir: src

nav:
- Build, deploy and maintain apps:
  - Build an application: docs/build-deploy-and-maintain-apps/build-an-application.md
  - Deploy an application: docs/build-deploy-and-maintain-apps/deploy-an-application.md
  - Image and artifact management with Artifactory: docs/build-deploy-and-maintain-apps/image-artifact-management-with-artifactory.md
  - Push and pull artifacts in Artifactory: docs/build-deploy-and-maintain-apps/push-pull-artifacts-artifactory.md
  - Set up an Artifactory project and repository: docs/build-deploy-and-maintain-apps/setup-artifactory-project-repository.md
  - Set up an Artifactory service account: docs/build-deploy-and-maintain-apps/setup-artifactory-service-account.md
  - Build with RHEL base images: docs/build-deploy-and-maintain-apps/build-with-rhel-base-images.md
  - Best practices for managing image streams: docs/build-deploy-and-maintain-apps/imagestreams.md
  - Prebuilt images: docs/build-deploy-and-maintain-apps/prebuilt-images.md
- Openshift projects and access:
  - Provision a new OpenShift project: docs/openshift-projects-and-access/provision-new-openshift-project.md
  - Grant user access in OpenShift: docs/openshift-projects-and-access/grant-user-access-openshift.md
  - Log in to OpenShift Web Console: docs/openshift-projects-and-access/login-to-openshift.md
  - Install the oc command line tool: docs/openshift-projects-and-access/install-the-oc-command-line-tool.md
- Use GitHub in BC Gov:
  - BC Government organizations in GitHub: docs/use-github-in-bcgov/bc-government-organizations-in-github.md
  - Remove a user's BCGov GitHub access: docs/use-github-in-bcgov/remove-user-bcgov-github-access.md
  - GitHub Enterprise user licences in the BC government: docs/use-github-in-bcgov/github-enterprise-user-licenses-bc-government.md
  - Evaluate open-source content: docs/use-github-in-bcgov/evaluate-open-source-content.md
  - Required pages for a GitHub repository: docs/use-github-in-bcgov/required-pages-for-github-repository.md
  - Start working in the BCGov GitHub organization: docs/use-github-in-bcgov/start-working-in-bcgov-github-organization.md
  - License your GitHub repository: docs/use-github-in-bcgov/license-your-github-repository.md
- Automation and resiliency:
  - CI/CD pipeline templates for Private Cloud teams: docs/automation-and-resiliency/cicd-pipeline-templates-for-private-cloud-teams.md
  - Application resiliency guidelines: docs/automation-and-resiliency/app-resiliency-guidelines.md
  - Application resource tuning: docs/automation-and-resiliency/application-resource-tuning.md
  - OpenShift project resource quotas: docs/automation-and-resiliency/openshift-project-resource-quotas.md
  - Request a quota increase for an OpenShift project set: docs/automation-and-resiliency/request-quota-increase-for-openshift-project-set.md
  - Argo CD usage: docs/automation-and-resiliency/argo-cd-usage.md  
  - Restoring Backup Volumes on OpenShift: docs/automation-and-resiliency/netapp-backup-restore.md
  - Prepare to load test an application on OpenShift: docs/automation-and-resiliency/prepare-to-load-test-application-on-openshift.md
  - Product Team Recovery Best Practices and Responsibilities: docs/automation-and-resiliency/namespace-recovery-and-responsibilities.md
- App monitoring:
  - Onboarding to application monitoring with Sysdig: docs/app-monitoring/sysdig-monitor-onboarding.md
  - Set up a team in Sysdig Monitor: docs/app-monitoring/sysdig-monitor-setup-team.md
  - Create alerts and notifications in Sysdig Monitor: docs/app-monitoring/sysdig-monitor-create-alert-channels.md
  - Set up advanced metrics in Sysdig Monitor: docs/app-monitoring/sysdig-monitor-set-up-advanced-functions.md
  - Check application health after an outage: docs/app-monitoring/check-application-health-after-outage.md
  - User Defined Monitoring in OpenShift: docs/app-monitoring/user-defined-monitoring.md
- Database and API management:
  - High availability database clusters: docs/database-and-api-management/high-availability-database-clusters.md
  - Open-source database technologies: docs/database-and-api-management/opensource-database-technologies.md
  - Database backup best practices: docs/database-and-api-management/database-backup-best-practices.md
- Security and privacy compliance:
  - Security best practices for apps: docs/security-and-privacy-compliance/security-best-practices-for-apps.md
  - Vault secrets management: docs/security-and-privacy-compliance/vault-secrets-management-service.md
  - Vault getting started guide: docs/security-and-privacy-compliance/vault-getting-started-guide.md
  - DevOps security considerations: docs/security-and-privacy-compliance/devops-security-considerations.md
  - Payment card processing for OpenShift applications: docs/security-and-privacy-compliance/payment-card-processing.md
- Reusable code and services:
  - Reusable services list: docs/reusable-code-and-services/reusable-services-list.md
- Platform architecture reference:
  - Platform Architecture Diagram: docs/platform-architecture-reference/platform-architecture-diagram.md
  - OpenShift network policies: docs/platform-architecture-reference/openshift-network-policies.md
  - Platform storage: docs/platform-architecture-reference/platform-storage.md
  - Set up TCP connectivity on the Private Cloud OpenShift Platform: docs/platform-architecture-reference/set-up-tcp-connectivity-on-private-cloud-openshift-platform.md
- Training and learning:
  - Training from the Platform Services Team: docs/training-and-learning/training-from-the-platform-services-team.md
  - External training resources: docs/training-and-learning/training-external-resources.md
- Design system:
  - About the design system: docs/design-system/about-the-design-system.md
- Rocketchat:
  - Join the B.C. Government Rocket.Chat: docs/rocketchat/steps-to-join-rocketchat.md
  - Rocket.Chat etiquette: docs/rocketchat/rocketchat-etiquette.md
  - Rocket.Chat channel descriptions: docs/rocketchat/rocketchat-channel-descriptions.md
  - Get help in Rocket.Chat: docs/rocketchat/get-help-in-rocketchat.md

plugins: 
- techdocs-core

exclude_docs: |
  drafts/
  components/
  hooks/
  pages/
  utils/
