name: Check if index file changed

permissions: write-all
  
on:
  pull_request_target:
    types:
      - opened
    branches: [ "main" ]


jobs:
  
  check-for-changed-file:
    runs-on: ubuntu-latest     

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Did index.md change?
        id: changed-index-file
        uses: tj-actions/changed-files@v38
        with:
          files: src/pages/index.js
      
      - name: Set PR Number
        if: steps.changed-index-file.outputs.any_changed == 'true'
        id: pr_number
        run: echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV

      - name: Create issue if changed file
        if: steps.changed-index-file.outputs.any_changed == 'true'
        run: gh issue create --title "Update homepage index.md file" --body "The upstream index.js file changed with PR#$PR_NUMBER. Update the [index.md](../../src/index.md) file to reflect the changes." --assignee MonicaG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}