name: Check if index file changed

on:
  push:
    branches: [ "main" ]

jobs:
  
  check-for-changed-file:
    runs-on: ubuntu-latest     

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Did index.md change?
        id: changed-index-file
        uses: tj-actions/changed-files@v38
        with:
          files: src/pages/index.js
      
      - name: Get commit
        if: steps.changed-index-file.outputs.any_changed == 'true'
        id: commit_sha
        run: |
          LAST_COMMIT_SHA=$(git log -n 1 --pretty=format:%H -- src/pages/index.js)
          echo "FILE_SHA=$LAST_COMMIT_SHA" >> $GITHUB_ENV

      - name: Create issue if changed file
        if: steps.changed-index-file.outputs.any_changed == 'true'
        run: gh issue create --title "Update file" --body "The src/pages/index.js file changed with latest push $FILE_SHA. Update the src/index.md to reflect the changes." --assignee MonicaG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}