name: Check if index file changed

on:
  pull_request:
    branches: [ "main" ]
    types: [opened]

jobs:
  
  check-for-changed-file:
    runs-on: ubuntu-latest     

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Did index.md change?
        id: changed-index-file
        uses: tj-actions/changed-files@v38
        with:
          files: src/pages/index.js
      
      - name: Set PR Number
        if: steps.changed-index-file.outputs.any_changed == 'true'
        id: pr_number
        run: echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV

      - name: Create issue if index.md changed
        if: steps.changed-index-file.outputs.any_changed == 'true'
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/ISSUE_TEMPLATE/homepage_changed.md