---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: route-patcher-
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "3"
  labels:
    jobType: patch
spec:
  activeDeadlineSeconds: 60
  backoffLimit: 2
  template:
    metadata:
      labels:
        jobType: patch
      annotations:
        vault.hashicorp.com/namespace: platform-services
        vault.hashicorp.com/role: VAULTROLE
        vault.hashicorp.com/auth-path: auth/k8s-CLUSTERNAME
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-inject-token: 'true'
        vault.hashicorp.com/agent-pre-populate-only: 'true'
        vault.hashicorp.com/agent-inject-secret-SECRETKEY: VAULTROLE/SECRETKEY
        vault.hashicorp.com/agent-inject-template-SECRETKEY: |
          {{ with secret "VAULTROLE/SECRETKEY" -}}
          export TLS_CERT="{{ .Data.data.certificate }}"
          export TLS_KEY="{{ .Data.data.key }}"
          {{- end }}
    spec:
      serviceAccount: LICENSEPLATE-vault
      serviceAccountName: LICENSEPLATE-vault
      restartPolicy: Never
      containers:
      - name: route-patcher
        image: 'artifacts.developer.gov.bc.ca/bcgov-docker-local/argocd-route-patcher:latest'
        args:
          - "sh"
          - "-c"
          - ". /vault/secrets/SECRETKEY && /patches/script/route-patcher.sh"
        volumeMounts:
        - name: route-patcher
          mountPath: /patches/script
      volumes:
      - name: route-patcher
        configMap:
          name: route-patcher
          defaultMode: 0754

