kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: route-patcher
subjects:
  - kind: ServiceAccount
    name: route-patcher
    namespace: NAMESPACE
  - kind: ServiceAccount
    name: LICENSEPLATE-vault
    namespace: NAMESPACE
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: route-patcher
