apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: route-patcher
rules:
  - apiGroups:
      - ''
      - route.openshift.io
    resources:
      - routes
      - routes/status
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ''
      - route.openshift.io
    resources:
      - routes/custom-host
    verbs:
      - create
      - update
